-- DROP DATABASE SS_PTS

CREATE DATABASE SS_PTS ON ( NAME = PTS, FILENAME = N'E:\Data\SS_PTS_NM.ss' ),
( NAME = PTS_DS01, FILENAME = N'E:\Data\SS_PTS_DS01.ss' ),
( NAME = PTS_DS02, FILENAME = N'E:\Data\SS_PTS_DS02.ss' )
 AS SNAPSHOT OF PTS;


-- DROP DATABASE SS_QnA
CREATE DATABASE SS_QnA ON ( NAME = QnA, FILENAME = N'E:\Data\SS_QnA_NM.ss' )
 AS SNAPSHOT OF QnA;
 
-- DROP DATABASE SS_AMS
CREATE DATABASE SS_AMS ON ( NAME = AMS, FILENAME = N'E:\Data\SS_AMS.ss' )
 AS SNAPSHOT OF AMS;

-- RESTORE DATABASE PTS FROM DATABASE_SNAPSHOT = 'SS_PTS';

-- RESTORE DATABASE AMS FROM DATABASE_SNAPSHOT = 'SS_AMS';
