-- RESTORE PTS FROM PROD
-- RESTORE FILELISTONLY FROM DISK = '\\asm.lan\dcshare\Backup\CA\SQL\Prod\CABIPV1\PTS_backup_2014_09_20_210012_1349833.bak' WITH FILE = 1
RESTORE DATABASE PTS
FROM DISK = N'\\asm.lan\dcshare\Backup\CA\SQL\Prod\CABIPV1\PTS_backup_2014_09_20_210012_1349833.bak' 
WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 10,
MOVE 'PTS'		TO 'E:\Data\PTS.mdf',
move 'PTS_DS01'	TO 'E:\Data\PTS_DS01.ndf',
move 'PTS_DS02'	TO 'E:\Data\PTS_DS02.ndf',
MOVE 'PTS_log'	TO 'E:\Log\PTS_log.LDF'


-- TAKE SNAPSHOT
CREATE DATABASE SS_PTS ON ( NAME = PTS, FILENAME = N'E:\Data\SS_PTS.ss' ),
( NAME = PTS_DS01, FILENAME = N'E:\Data\SS_PTS_DS01.ss' ),
( NAME = PTS_DS02, FILENAME = N'E:\Data\SS_PTS_DS02.ss' )
 AS SNAPSHOT OF PTS;