-- RESTORE FILELISTONLY FROM DISK = '\\asm.lan\dcshare\Backup\CA\SQL\Prod\CABIPV1\QnA_backup_2014_09_20_210012_1973925.bak' WITH FILE = 1
-- RESTORE QnA FROM PROD
RESTORE DATABASE QnA
FROM DISK = N'\\asm.lan\dcshare\Backup\CA\SQL\Prod\CABIPV1\QnA_backup_2014_09_20_210012_1973925.bak' 
WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 10,
MOVE 'QnA'		TO 'E:\Data\QnA.mdf',
MOVE 'QnA_log'	TO 'E:\Log\QnA_log.LDF'
GO

-- TAKE SNAPSHOT
CREATE DATABASE SS_QnA ON ( NAME = QnA, FILENAME = N'E:\Data\SS_QnA.ss')
AS SNAPSHOT OF QnA;
GO



-- RESTORE FILELISTONLY FROM DISK = '\\asm.lan\dcshare\Backup\CA\SQL\Prod\CABIPV1\Encompass_backup_2014_10_08_030001_6094358.bak' WITH FILE = 1
-- RESTORE QnA FROM PROD
RESTORE DATABASE Encompass
FROM DISK = N'\\asm.lan\dcshare\Backup\CA\SQL\Prod\CABIPV1\Encompass_backup_2014_10_08_030001_6094358.bak' 
WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 10,
MOVE 'Encompass'		TO 'E:\Data\Encompass.mdf',
MOVE 'Encompass_log'	TO 'E:\Log\Encompass_log.LDF'
GO